ReservaVan.Motorista.Web/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using ReservaVan.Motorista.Domain.Interfaces.Repositories;
using ReservaVan.Motorista.Web.Models.ViewModels;

namespace ReservaVan.Motorista.Web.Controllers;

public partial class LoginController : ControllerBase
{
    [HttpGet]
    public IActionResult Index(string returnUrl)
    {
        var model = new LoginViewModel();
        model.ReturnUrl = returnUrl;

        return View(model);
    }

    public async Task<IActionResult> Index(LoginViewModel model) 
    {
        model.ReturnUrl ??= Url.Content("~/");

        if (!ModelState.IsValid)
        {
            model.ModelStateErrors = ModelState
                .Where(x => x.Value.Errors.Count > 0)
                .SelectMany(x => x.Value.Errors, (x, y) => y.ErrorMessage)
                .ToList();

            return View(model);
        }

        var usuario = await _unitOfWork.UsuarioRepository.FindByEmailAsync(model.Email);
        if (usuario == null)
        {
            model.ModelStateErrors.Add("E-mail não existe cadastrado ou senha está incorreta");

            return View(model);
        }

        var senhaEstaCorreta = await _unitOfWork.UsuarioRepository.CheckPasswordAsync(usuario, model.Password);
        if (!senhaEstaCorreta)
        {
            model.ModelStateErrors.Add("E-mail não existe cadastrado ou senha está incorreta");

            return View(model);
        }

        await _unitOfWork.SignInRepository.SignInAsync(usuario, false);

        return LocalRedirect(model.ReturnUrl);
    }
}

public partial class LoginController
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly ILogger<LoginController> _logger;

    public LoginController(
        IUnitOfWork unitOfWork,
        ILogger<LoginController> logger
    )
    {
        _unitOfWork = unitOfWork;
        _logger = logger;
    }
}

ReservaVan.Motorista.Web/Controllers/LogoutController.cs
using Microsoft.AspNetCore.Mvc;
using ReservaVan.Motorista.Domain.Interfaces.Repositories;

namespace ReservaVan.Motorista.Web.Controllers;

public partial class LogoutController : ControllerBase
{
    [HttpGet]
    public async Task<IActionResult> Index()
    {
        await _unitOfWork.SignInRepository.SignOutAsync();
        
        return RedirectToAction("Index", "Home");
    }
}

public partial class LogoutController
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly ILogger<LogoutController> _logger;

    public LogoutController(
        IUnitOfWork unitOfWork,
        ILogger<LogoutController> logger
    )
    {
        _unitOfWork = unitOfWork;
        _logger = logger;
    }
}

ReservaVan.Motorista.Web/Controllers/PrivacidadeController.cs
using Microsoft.AspNetCore.Mvc;

namespace ReservaVan.Motorista.Web.Controllers;

public class PrivacidadeController : ControllerBase
{
    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }
}

ReservaVan.Motorista.Web/Controllers/RegistreController.cs
using Microsoft.AspNetCore.Mvc;
using ReservaVan.Motorista.Application.DTOs;
using ReservaVan.Motorista.Application.Interfaces.ApplicationServices;
using ReservaVan.Motorista.Web.Models.ViewModels;

namespace ReservaVan.Motorista.Web.Controllers;

public partial class RegistreController : ControllerBase
{
    [HttpGet]
    public IActionResult Index()
    {
        return View(new RegistreViewModel());
    }

    [HttpPost]
    public async Task<IActionResult> Index(RegistreViewModel model)
    {
        if (!ModelState.IsValid)
        {
            model.Errors = ModelState.Keys.SelectMany(key => ModelState[key]!.Errors.Select(x => $"{key}: {x.ErrorMessage}"));
            return View(model);
        }

        model.ReturnUrl ??= Url.Content("~/");
        //model.ExternalLogins = (await _unitOfWork.SignInRepository.GetExternalAuthenticationSchemesAsync()).ToList();

        var user = new RegisterUsuarioRequest();
        user.Email = model.Email!;
        user.Password = model.Password!;
        user.Nome = model.Nome!;
        user.Sobrenome = model.Sobrenome!;
        user.DataNascimento = model.DataNascimento!.Value;

        var result = await _usuarioAppSvc.Register(user);
        if (result.Errors.Any())
        {
            model.Errors = result.Errors.ToList();
            return View(model);
        }

        return LocalRedirect(model.ReturnUrl);
    }
}

public partial class RegistreController
{
    private readonly IUsuarioAppSvc _usuarioAppSvc;
    private readonly ILogger<RegistreController> _logger;

    public RegistreController(
        IUsuarioAppSvc usuarioAppSvc,
        ILogger<RegistreController> logger
    )
    {
        _usuarioAppSvc = usuarioAppSvc;
        _logger = logger;
    }
}

ReservaVan.Motorista.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ReservaVan.Motorista.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ReservaVan.Motorista.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <partial name="_MenuPartial" />
        </nav>
    </header>
    
    <main role="main" class="container pb-3">
        @RenderBody()
    </main>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ReservaVan.Motorista.Web - <a asp-area="" asp-controller="Privacidade" asp-action="Index">Privacidade</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ReservaVan.Motorista.Web/Views/Shared/_MenuPartial.cshtml
@using Microsoft.AspNetCore.Identity;
@using ReservaVan.Motorista.Domain.Entities;
@using ReservaVan.Motorista.Web.Extensions;

@inject SignInManager<Usuario> _signInManager;

<div class="container-fluid">
    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ReservaVan - Motorista</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
        @if (_signInManager.IsSignedIn(User)) {
            <ul class="navbar-nav flex-grow-1 justify-content-end">
                <li class="nav-item">
                    <span class="nav-link text-dark d-inline-block">Seja bem vindo, @User.Identity.Nome()</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="DadosPessoais" asp-action="Index">Dados Pessoais</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Logout" asp-action="Index">Logout</a>
                </li>
            </ul>
        }
        else
        {
            <ul class="navbar-nav flex-grow-1 justify-content-end">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Registre" asp-action="Index">Registre-se</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                </li>
            </ul>
        }
    </div>
</div>